// FrontendDevelopment/handson_06/student-portal-react/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {
  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <header className="header">
      <div className="logo">
        <h2>🎓 Student Portal</h2>
      </div>

      <nav>
        <ul className="nav-links">
          <li>
            <Link to="/">Home</Link>
          </li>

          <li>
            <Link to="/courses">Courses</Link>
          </li>

          <li>
            <Link to="/profile">
              Profile ({enrolledCourses.length})
            </Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}

export default Header;

// FrontendDevelopment/handson_08/student-portal-vue/src/components/Header.vue
<template>
  <header class="header">
    <h2>🎓 Student Portal</h2>

    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">
        Profile ({{ store.enrolledCourses.length }})
      </RouterLink>
    </nav>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
.header{
    background:#1976d2;
    color:white;
    padding:18px 35px;

    display:flex;
    justify-content:space-between;
    align-items:center;
}

nav{
    display:flex;
    gap:25px;
}

a{
    color:white;
    text-decoration:none;
    font-weight:bold;
}

a:hover{
    color:#ffd54f;
}
</style>
